apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # New user: sameer (in addition to existing admin)
  accounts.sameer: apiKey, login
  admin.enabled: "true"
  url: "https://localhost:8080"
